### ISSUE TITLE
Why This File ? 

### ISSUE THREAD

**Issue by VarnaX** [mjishnu/pypdl#16]
Why [__init__.py](https://github.com/mjishnu/pypdl/blob/main/__init__.py) in repo ?
blank file ?

**Comment by mjishnu** [comment]
> Why [**init**.py](https://github.com/mjishnu/pypdl/blob/main/__init__.py) in repo ? blank file ?

that is need for pypi. since pypdl is also a pypi package it need to follow the file structure set by pypi

**Comment by VarnaX** [comment]
No, [this file](https://github.com/mjishnu/pypdl/blob/main/pypdl/__init__.py) enough to pypi.
no need to [this file](https://github.com/mjishnu/pypdl/blob/main/__init__.py). Check other pypi libraries.

**Comment by mjishnu** [comment]
> No, [this file](https://github.com/mjishnu/pypdl/blob/main/pypdl/__init__.py) enough to pypi. no need to [this file](https://github.com/mjishnu/pypdl/blob/main/__init__.py). Check other pypi libraries.

you are correct that file was unwanted, removed it. it was a file i created when i was learning to create pypi packages or something. i was under the impression that it was need lol, thanks for reporting!
