### ISSUE TITLE
Segments cannot be merged, the download process is stuck and cannot be completed

### ISSUE THREAD

**Issue by minhpn** [mjishnu/pypdl#18]
- I encounter an issue like the image below
<img width="870" alt="CleanShot 2024-04-29 at 16 32 30@2x" src="https://github.com/mjishnu/pypdl/assets/10785236/84652814-f8d6-4119-b4b7-b3714188feaa">

- being blocked indefinitely like this and unable to continue
<img width="345" alt="CleanShot 2024-04-29 at 16 32 52@2x" src="https://github.com/mjishnu/pypdl/assets/10785236/a2bb21fe-0aa1-4c81-800d-caa92c9e5d00">

- i using default:
`dl.start(
    url='http://example.com/file.txt',
    file_path='file.txt',
    segments=10,
    display=True,
    multithread=True,
    block=True,
    retries=0,
    mirror_func=None,
    etag=True
)`

**Comment by mjishnu** [comment]
can you test using this version and see if its still happening [https://test. pypi.org/project/pypdl/](https://test. pypi.org/project/pypdl/)

**Comment by minhpn** [comment]
I'm trying out version 1.4.1, there's a minor syntax error. I've temporarily fixed it and I'm testing to see if the issue I encountered before still persists. Thank you!
![CleanShot 2024-05-02 at 10 21 42](https://github.com/mjishnu/pypdl/assets/10785236/ea640e11-77f1-4595-a231-feaf7559a990)
![CleanShot 2024-05-02 at 10 19 35](https://github.com/mjishnu/pypdl/assets/10785236/487e316d-ea06-46aa-bacf-3e314ec8492f)

**Comment by mjishnu** [comment]
can you provide the full error traceback
