### ISSUE TITLE
Really dumb question, dont know where else to post it - sorry.

### ISSUE THREAD

**Issue by harryeffinpotter** [mjishnu/pypdl#6]
Can this repo be used to serve files to users over my fastapi or flask app? Or is it only for end users, not for serving whatsoever. Thanks for answering in advance my super dumb question.

**Comment by m-jishnu** [comment]
it should work i haven't personally tried on fastapi or flask api but generally it should work.

**Comment by m-jishnu** [comment]
hello did it work?

**Comment by harryeffinpotter** [comment]
I haven tried yet, my stack is kinda complicated at this point I'll lyk
I'll be trying later hopefully
